repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: .venv/bin/mypy app
        language: system
        types: [python]
        pass_filenames: false

      - id: gitleaks
        name: gitleaks
        entry: gitleaks protect --staged --config .gitleaks.toml
        language: system
        pass_filenames: false

      - id: bandit
        name: bandit
        entry: .venv/bin/bandit -r app -ll
        language: system
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: .venv/bin/pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
